DFRobotMaqueenPlus.I2CInit()
basic.forever(function () {
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.RED)
    basic.pause(1000)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.RED)
    basic.pause(1000)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.RED)
    basic.pause(1000)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.RED)
    basic.pause(1000)
})
basic.forever(function () {
    music.startMelody(music.builtInMelody(Melodies.Ringtone), MelodyOptions.Forever)
    basic.pause(1000)
    music.stopAllSounds()
    basic.pause(500)
    music.startMelody(music.builtInMelody(Melodies.Ringtone), MelodyOptions.Forever)
    basic.pause(1000)
    music.stopAllSounds()
    basic.pause(500)
})
basic.forever(function () {
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 50)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CCW, 50)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
})
basic.forever(function () {
	
})
